---
 - hosts: all
   tasks:
   - name: Clone a github repository
     git:
       repo: https://{{gituser}}:{{gitpass}}@github.com/centroidcloudteam/ms-tools.git
       dest: /tmp/
       clone: yes
       update: yes
   
   - name: Start app
     ansible.builtin.shell: cd /tmp/ && rm -rf ms-tools && git clone https://{{gituser}}:{{gitpass}}@github.com/centroidcloudteam/ms-tools.git
     
