- name: services stop start
  hosts: all
#  var:
#  - APP_OWNER: "{{'ora'+SID|lower }}"

  roles:
  - {role: start-app, tags: start-app, remote_user: "{{APP_OWNER}}"}
  - {role: stop-app, tags: stop-app, remote_user: "{{APP_OWNER}}"}
